### ISSUE TITLE
simple queues target

### ISSUE THREAD

**Issue by Two-Two-One** [MadaMzandu/uisp-ros-plugin#4] opened 2021-12-06 17:35 UTC
in simple queues in mikrotik the target is the interface name not ip that is target =<pppoe user> instead of target= ip_address

**Comment by MadaMzandu** [comment] 2021-12-07 06:53
Mikrotik simple queues support both an ip address and an interface as a target. Can you please describe the problem?

**Comment by Two-Two-One** [comment] 2021-12-07 08:29
When the simple queues are created instead of ip in target it has pppoe interface instead. See attached screenshot

**Comment by MadaMzandu** [comment] 2021-12-07 11:09
Yes this is normal operation. The dynamic queue is applied on the clients pppoe interface. Are the queues failing to catch the client's traffic?

**Comment by Two-Two-One** [comment] 2021-12-07 11:15
Yes

**Comment by MadaMzandu** [comment] 2021-12-07 11:40
Ok will check and get back to you.

**Comment by Two-Two-One** [comment] 2021-12-07 11:43
Thanks. If I manually put an ip there just to test. The queue works

**Comment by MadaMzandu** [comment] 2021-12-07 12:53
Thanks for bring this to my attention. I can confirm that this is a bug caused by the first child of the parent queue.

I have have made an emergency release https://github.com/MadaMzandu/uisp-ros-plugin/blob/main/src/ros-plugin.zip which has  a temporary fix. To apply do the following:

1. Install the new zip.
2. On your mikrotiks delete every queue that has 1stchild packet mark
3. In panel > settings > system run the rebuild utility to apply the fix.

A permanent fix will be included in the next release. Let me know how that goes.

**Comment by Two-Two-One** [comment] 2021-12-07 13:46
Thanks

**Comment by alvianx** [comment] 2021-12-24 18:33
Hi @MadaMzandu, I'm testing the temporary fix and can confirm the simple queues still doesn't work.

> Thanks for bring this to my attention. I can confirm that this is a bug caused by the first child of the parent queue.
> 
> I have have made an emergency release https://github.com/MadaMzandu/uisp-ros-plugin/blob/main/src/ros-plugin.zip which has a temporary fix. To apply do the following:
> 
>     1. Install the new zip.
> 
>     2. On your mikrotiks delete every queue that has 1stchild packet mark
> 
>     3. In panel > settings > system run the rebuild utility to apply the fix.
> 
> 
> A permanent fix will be included in the next release. Let me know how that goes.

**Comment by alvianx** [comment] 2021-12-28 04:22
Try changing the servicePlan-parent queues from 0.0.0.0./0 to your IP pools subnet on plugin device config seems to fix the queue problem

**Comment by MadaMzandu** [comment] 2021-12-29 19:04
Thanks for the update. You are right I think I should apply the pool to the parent will do that next version after new year.

**Comment by MadaMzandu** [comment] 2022-01-04 09:23
I have tested this on ROS 6.x and parent target 0.0.0.0/0 does not appear to be a problem as long as first child is fixed.

**Comment by MadaMzandu** [comment] 2022-01-19 05:11
A permanent fix has been applied. The children ip addresses are now set as the parent target and the standby child queue has been removed.

**Closed** 2022-01-21 11:44 UTC
